baseurl: "http://nobu666.com/"
languageCode: "ja-JP"
title: "Real Beat"
theme: "vienna"
paginate: 10
uglyurls: true
copyright: "&copy; nobu666.com"
disqusShortname: "realbeat"
rssuri: "feed.xml"
hasCJKLanguage: true
pygmentscodefences: true
pygmentsstyle: "monokai"

params:
  author: "nobu666"
  avatar: "https://avatars0.githubusercontent.com/u/51591?v=3&s=460"
  contact: "mailto:ogata.nobu at gmail.com"
  bio: ""
  subtitle: ""

  twitter: "nobu666"
  facebook: "nobutoshi.ogata"
  github: "nobu666"
  linkedin: "nobu666"
  stackoverflow: ""
  ga_api_key: "UA-57485-1"
  mixpanel_api_key: ""
